---

- name: Add SystemD file for setting MariaDB limits
  template: 
    src: "mariadb_limits.cnf.j2" 
    dest: "/etc/systemd/system/mariadb.service.d/limits.conf"
    owner: "root"
    group: "root" 
    mode: "0644"
  notify: SystemD Daemon reload