---

- name: Add main MySQL configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
    owner=root group=root mode=0644
  notify: Restart Mysql service on cluster node

- name: Add Galera node configuration
  template: src=node.cnf.j2 dest={{ mysql_config_folder }}/node.cnf
    owner=root group=root mode=0644
  when: cluster_configuration != 'standalone'
  notify: Restart Mysql service on cluster node

- name: Add MySQL daemon configuration
  template: src=mysqld.cnf.j2 dest={{ mysql_config_folder }}/mysqld.cnf
    owner=root group=root mode=0644
  notify: Restart Mysql service on cluster node

- name: Add MySQL replication configuration
  template: src=async.cnf.j2 dest={{ mysql_config_folder }}/async.cnf
    owner=root group=root mode=0644
  notify: Restart Mysql service on cluster node

- name: Add Audit logs configuration
  template: src=audit.cnf.j2 dest={{ mysql_config_folder }}/audit.cnf
    owner=root group=root mode=0644
  notify: Restart Mysql service on cluster node

- name: Add galera cluster configuration
  template: src=galera.cnf.j2 dest={{ mysql_config_folder }}/galera.cnf
    owner=root group=root mode=0644
  when: cluster_configuration != 'standalone'
  notify: Restart Mysql service on cluster node

- name: Add MySQL Innodb configuration
  template: src=innodb.cnf.j2 dest={{ mysql_config_folder }}/innodb.cnf
    owner=root group=root mode=0644
  notify: Restart Mysql service on cluster node
