#!/bin/sh
/usr/sbin/logrotate /etc/logrotate.d/nginx
EXITVALUE1=$?
/usr/sbin/logrotate /etc/logrotate.hourly.conf
EXITVALUE2=$?
if [ $EXITVALUE1 != 0  ] || [ $EXITVALUE2 != 0  ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0