---
- name: Install the epel-release package.
  yum:
    name: epel-release
    state: present

- name: Import EPEL RPM GPG key.
  rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ centos_release }}"
