# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.9.0"

Vagrant.configure("2") do |config|

  unless Vagrant.has_plugin?("vagrant-cachier")
    raise Vagrant::Errors::VagrantError.new, "Plugin missing: vagrant plugin install vagrant-cachier"
  end
  config.cache.scope = :box

  config.vm.define "dev-env-deb" do |db|
    db.ssh.insert_key = false
    db.vm.box = "debian-11.0.0-amd64-js"
    db.vm.box_check_update = true
    db.vm.hostname = "dev-env-deb"
    db.vm.network(:private_network, {
      ip: "192.168.49.12",
      auto_config: true
    })
    db.vm.synced_folder ".", "/vagrant", disabled: true
    db.vm.synced_folder "C:/Users/Zhora/my_projects", "/vagrant"
    db.vm.provision "shell", inline: <<-SHELL
      hostnamectl set-hostname dev-env-deb.local
      hostnamectl status
      echo "dev-env-deb.local" >> /etc/hostname
    SHELL
  end
end
