apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.app_name }}
  labels:
    chart: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
      - name: {{ .Values.app_name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: KAFKA_HOST
          value: {{ .Values.kafka.server }}
        - name: READ_FILE
          value: {{ .Values.kafka.read_file }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "150m"
