---
- name: Setting hostname on Centos 6/7
  block:
    - template:
        src: "{{ item }}.j2"
        dest: /etc/sysconfig/{{ item }}
        mode: 0644
        owner: root
        group: root
      with_items:
        - network
      when: ansible_distribution_major_version | int == 6
      notify:
        - reboot
        - smoke management ip
    - template:
        src: "{{ item }}.j2"
        dest: /etc/{{ item }}
        mode: 0644
        owner: root
        group: root
      with_items: 
        - hostname
      when: ansible_distribution_major_version | int >= 7
    - shell: "hostnamectl set-hostname {{ inventory_hostname }}"
      when: ansible_distribution_major_version | int >= 7
  when: ansible_distribution == 'CentOS'
