# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.9.0"

Vagrant.configure("2") do |config|

  unless Vagrant.has_plugin?("vagrant-cachier")
    raise Vagrant::Errors::VagrantError.new, "Plugin missing: vagrant plugin install vagrant-cachier"
  end
  config.cache.scope = :box

  (1..2).each do |i|
    config.vm.define "kube-#{i}" do |kube|
      kube.ssh.insert_key = false
      kube.vm.box = "debian-11.0.0-amd64-js"
      kube.vm.box_check_update = true
      kube.vm.hostname = "kube-#{i}.local"
      kube.vm.network(:private_network, {
        ip: "192.168.49.3#{i}",
        auto_config: true
      })
      kube.vm.provision "shell", inline: <<-SHELL
        hostnamectl set-hostname kube-#{i}.local
        hostnamectl status
        echo "kube-#{i}.local" >> /etc/hostname
      SHELL
    end
  end
end
